/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semana03;

/**
 *
 * @author u
 */
public class ejer05 extends javax.swing.JFrame {

    /**
     * Creates new form ejer05
     */
    public ejer05() {
        initComponents();
        this.setSize(300, 200);
        this.setTitle("Mi primer APP");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_mensaje = new javax.swing.JLabel();
        bt_presionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_mensaje.setText("Presiona el botón");
        getContentPane().add(jl_mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        bt_presionar.setText("Haz clic Aqui");
        bt_presionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_presionarActionPerformed(evt);
            }
        });
        getContentPane().add(bt_presionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_presionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_presionarActionPerformed
        // TODO add your handling code here:
        jl_mensaje.setText("Hola desde Java Swing");
    }//GEN-LAST:event_bt_presionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejer05.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejer05().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_presionar;
    private javax.swing.JLabel jl_mensaje;
    // End of variables declaration//GEN-END:variables
}
